### ISSUE TITLE
Edit the timelog by daily schedule table.

### ISSUE THREAD

**Issue by james-jhang** [software-system-lab/timelog#14]
This is a suggestion, that I want to edit my weekly time log in a way like a daily schedule table, as the picture below.
![image](https://user-images.githubusercontent.com/20788456/77377764-10fde300-6daf-11ea-9dc5-b6276e456879.png)

Currently, it is hard to check if I miss logs to record. If there is a daily schedule, I can check the logs each day more intuitively.

Thank you.

**Comment by Nightlord851108** [comment]
Hello, 

This is more likely the new service we are going to develop in the future, and Timelog will follow up to interact with it.
