### ISSUE TITLE
Unintuitive selection panel for showing spent time on dashboard.

### ISSUE THREAD

**Issue by james-jhang** [software-system-lab/timelog#16]
Not sure how others think of this, but I thought it is not easy to understand what the panel at the right-bottom corner means.

![image](https://user-images.githubusercontent.com/20788456/77378278-8f0eb980-6db0-11ea-90bb-a875c873d1bd.png)

This panel contains two functions, one is for filtering the period of the spent time, which affects the presentation of the dashboard page only; another one is about the timebox, which also affects the presentation of the dashboard page, and in addition, could be an individual function as the dashboard or the history page.

Free feel to discuss, thank you.

**Comment by Nightlord851108** [comment]
Do you actually mean the "left"-bottom corner? LOL

Okay, this is actually a UX issue, and it'll be improved in the new version.
