### ISSUE TITLE
Unit of selecting time.

### ISSUE THREAD

**Issue by james-jhang** [software-system-lab/timelog#17]
Could we have another way to select the time for a log? It is too fragmentary to select the time by every minute, i.e., 12, 13, 14, etc. 

Selecting by every half hour could be better.

P.S. I'm not sure if the "unit" is proper for the meaning I want to point out. Correct it if you have a better one.

Thank you.

**Comment by timchang1005** [comment]
after discussion, we decide to make "5 minutes" as a unit
