### ISSUE TITLE
Show 7 days for every week.

### ISSUE THREAD

**Issue by james-jhang** [software-system-lab/timelog#21]
Hi,

When I was recording logs, I'd like to see 7 days on every week. For example, 

2020-05-25 16:10:00 ~ 2020-05-25 18:07:00
 -> 2020-05-25 (Mon.) 16:10:00 ~ 2020-05-25 (Mon.) 18:07:00

2020-05-28 19:30:00 ~ 2020-05-29 00:22:00
 -> 2020-05-28 (Thur.) 19:30:00 ~ 2020-05-29 (Fri.) 00:22:00

I think that putting the 7-days for every week will make the Timelog more usable.

Thank you!

**Comment by Nightlord851108** [comment]
Can you describe more precisely about on which part you want to see week day?
Or do you mean wherever it shows a date, it should show the week day?

**Comment by james-jhang** [comment]
@Nightlord851108 Thanks for your reply. I think it'll be nice if we add it to the duration of the logs on the "History" page.

**Comment by timchang1005** [comment]
fixed!!!
