### ISSUE TITLE
No support for Chinese characters.

### ISSUE THREAD

**Issue by james-jhang** [software-system-lab/timelog#23]
As title, 
![image](https://user-images.githubusercontent.com/20788456/86730626-5219ba80-c061-11ea-8656-e7fbf9c8ec0c.png)

I didn't check other pages, so I'm not sure if there is any page that the same problem happens.

Thank you.

**Comment by Nightlord851108** [comment]
@james-jhang 

This repository is deprecated. 
Please report at the new repository.

Link to the new repository: https://github.com/software-system-lab/timelog_web/issues

Thanks.
